myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('<slug:slug>', views.post_page, name="page"),
]

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    def __str__(self):
        return self.title

myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("Hello World! I'm Home.")
    return render(request, 'home.html')


def about(request):
    # return HttpResponse("My About page.")
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render
from .models import Post


# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html',
                  {'posts': posts})


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html',
                  {'post': post})

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <img
                class="banner"
                src="{{ post.banner.url }}"
                alt="{{ post.title }}"/>
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
        <h1>Posts</h1>

        {% for post in posts %}
            <article class="post">
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                        {{ post.title }}
                    </a>
                </h2>
                <p>{{ post.date }}</p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> Page.</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">
            <span role="img" aria-label="Home">🏠</span>
        </a> |
        <a href="/about">😊</a> |
        <a href="{% url 'posts:list' %}">📑</a>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>